### ISSUE TITLE
ok/cancel overflow window but not accessible on mobile

### ISSUE THREAD

**Issue by hungtuchen** [g0v/ppt#31]
![11827054_864226280326994_1047270133_o](https://cloud.githubusercontent.com/assets/7189930/9113429/1f152e70-3c87-11e5-8cd9-a9a8e5d5e04d.jpg)

**Comment by hungtuchen** [comment]
update on material-ui
https://github.com/callemall/material-ui/pull/1266
https://github.com/callemall/material-ui/issues/667

**Comment by MrOrz** [comment]
Applying the https://github.com/callemall/material-ui/tree/update-datepicker branch does solve the problem on iPhone 5:
<img width="372" alt="2015-08-09 9 13 39" src="https://cloud.githubusercontent.com/assets/108608/9153197/90c71b42-3e7a-11e5-85f9-f67d2ea2e4ff.png">

However the dialog window position is too low. On iPhone 4 the buttons are still cropped. The vertical spacing on top of the dialog is composed of 16px of ["minimal top padding"](https://github.com/callemall/material-ui/blob/master/src/dialog.jsx#L309) and 64px of space to do the ["fade-and-drop" transition animation](https://github.com/callemall/material-ui/blob/master/src/dialog.jsx#L32). I currently think of no solution on such a small screen like iPhone 4's.
