### ISSUE TITLE
Error: Timeout in connecting after 5000 ms for pg

### ISSUE THREAD

**Issue by hungtuchen** [g0v/ppt#6]
It's weird that tables and all row are already constructed, however when I send request:
it got this, even if it's in localhost
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Timeout in connecting after 5000 ms",
    "stack": "Error: Timeout in connecting after 5000 ms\n    at [object Object].<anonymous> (/Users/mac/GitHub/edward_ptt/node_modules/loopback-datasource-juggler/lib/datasource.js:2029:10)\n    at [object Object]._onTimeout (/Users/mac/GitHub/edward_ptt/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)\n    at Timer.listOnTimeout (timers.js:89:15)"
  }
}

**Comment by hungtuchen** [comment]
Today, I tired it again.
when I use autoupdate in server/boot/mock-data.js, all the get methods work
but if I change to automigrate, then the same error happens again.

**Comment by MrOrz** [comment]
We're changing to express / sequelize, thus closing this issue for now. We'll revisit this issue if such bug is still reproducible.
